fullnameOverride: "baseline"
enableTraefikDashboard: true

AWS:
  region: us-west-2
  accountId: "918169021225"
  event_bridge_key_id: AKIA5LRZDNMU4ZLQOZSM
  event_bridge_key_secret: 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
  event_bus_arn: arn:aws:events:us-west-2:918169021225:event-bus/pvt-hv-wddl-wdev-ml-bus
  eventbridge_hostname: https://pvt-k8s-hv-wdev-wddl-uw2-1.wdev.hticdev.net/eventbridge
  auth_hostname: https://pvt-k8s-hv-wdev-wddl-uw2-1.wdev.hticdev.net/auth
  authServiceCookieOptionsDomain: pvt-k8s-hv-wdev-wddl-uw2-1.wdev.hticdev.net
  sqs_url_arn: https://sqs.us-west-2.amazonaws.com/918169021225/pvt-sqs-wddl-wdev-training-assets-verification-uw2-q
  sqs_name: pvt-sqs-wddl-wdev-training-assets-verification-uw2-q
dockerCredentials:
  username: HanwhaAutomation
  token: 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

graphql:
  hasuraToken: iw0vKKDTDo8gSs3Mwhaq3rOq
  databasePassword: _ePhp3URwD1laXjDDPzCWg.~
  databaseName: graphqlpvt
  databaseUser: graphqlpvt
  databaseHost: db-hv-wdev-wddl-uw2-1.cathbpeuoycp.us-west-2.rds.amazonaws.com

# https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
traefik:
  deployment:
    kind: Deployment
  image:
    pullPolicy: Always
  service:
    type: NodePort
  ports:
    web:
      # port to alb
      nodePort: 32414
      targetPort: web

# https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/charts/aws-efs-csi-driver/values.yaml
aws-efs-csi-driver:
  controller:
    serviceAccount:
      create: true
      name: efs-csi-controller-sa
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::918169021225:role/pvt-k8s-hv-wdev-wddl-uw2-1-cluster-basicrole
  storageClasses:
    - name: efs-storageclass
      mountOptions:
        - tls
      parameters:
        provisioningMode: efs-ap
        fileSystemId: fs-0c0a36d725a10d757

postgresql:
  service:
    type: ClusterIP
  resources:
    requests:
      cpu: 100m
      memory: 250Mi
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
  postgres:
    db: postgres
    user: postgres
    password: zD-.xBOMEZl37jPBvB-aUJ07
    replicaCount: 1
    repository: postgres
    tag: 14
    pullPolicy: Always
    containerPort: 5432
    env:
      # https://hub.docker.com/_/postgres
      - name: PGDATA
        value: /var/lib/postgresql/data/postgres # # To enable EFS on the cluster, use the following values in the root helm chart
  RDS:
    host: db-hv-wdev-wddl-uw2-1.cathbpeuoycp.us-west-2.rds.amazonaws.com
