{{- if ((.Values.image).domainPath) -}}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: "{{ include ".helm.fullname" . }}-strip"
  namespace: {{ .Values.namespace }}
spec:
  stripPrefixRegex:
    regex:
      - "/{{ .Values.image.domainPath }}"
{{ end }}