{{ if and (ne .Values.image.domainPath "") (not (hasKey .Values.image "noStripPath")) }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: "{{ include ".helm.fullname" . }}-strip"
  namespace: {{ .Values.namespace }}
spec:
  stripPrefix:
    prefixes:
      - "/{{ .Values.image.domainPath }}"
#      - "/license"
      # - "/help"
      # - "/project/:id"
    redirectRegex:
      regex: {{ .Values.image.domainPath }}/help
      replacement: https://support.hanwhavisionamerica.com/hc/en-us/articles/21707499681947-Welcome-Guide-for-Flex-AI
{{ end }}
