edgeauth:
  replicaCount: 1
  repository: ghcr.io/htaic/rest_auth_service
  tag: latest
  pullPolicy: Always
  containerPort: 3001
  domainPath: "v0.1/oauth"

imagePullSecrets:
  - name: dockerconfigjson-github-com

service:
  type: ClusterIP

resources:
  requests:
    cpu: 250m
    memory: 750Mi

serviceAccount:
  create: false
  annotations: {}
  name: ""
  
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80