apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include ".helm.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include ".helm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.hasura.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include ".helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include ".helm.selectorLabels" . | nindent 8 }}
    spec:
      hostname: {{ .Values.hasura.hostname }}
      serviceAccountName: {{ include ".helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.postgresProvisioner }}
      initContainers:
        - name: {{ .Chart.Name }}-postgres-provisioner
          {{- if hasKey .Values.postgresProvisioner "tag" }}
          image: {{ .Values.postgresProvisioner.image }}:{{ .Values.postgresProvisioner.tag }}
          {{ else }}
          image: {{ .Values.postgresProvisioner.image }}:latest
          {{ end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ['sh', '-c', '/home/developer/executecommands.sh']
          envFrom:
            - secretRef:
                name: "baseline-postgresql-secret"
            - secretRef:
                name: "graphql-postgresql-secret"
            - configMapRef:
                name: "baseline-configmap"
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.hasura.repository }}:{{ .Values.hasura.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.hasura.pullPolicy }}
          {{- if .Values.hasura.env }}
          env: 
            {{- toYaml .Values.hasura.env | nindent 12 }}
          {{- end }}
          args: [ {{.Values.hasura.args}} ]
          ports:
            - name: http
              containerPort: {{ .Values.hasura.containerPort }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /{{ .Values.hasura.livenessProbe }}
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /{{ .Values.hasura.readinessProbe }}
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}    
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
