apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: "{{ include ".helm.fullname" . }}-headers"
  namespace: {{ .Values.namespace }}
spec:
  headers:
    accessControlAllowMethods:
      - "GET"
      - "POST"
      - "OPTIONS"
    accessControlAllowOriginListRegex:
      - "http(s)?://localhost(:\\d+)?"
    accessControlAllowHeaders:
      - "authorization"
      - "content-type"
    accessControlMaxAge: 100
    addVaryHeader: true