apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include ".helm.serviceAccountName" . }}-pre-job-sa
  namespace: "{{ .Values.namespace }}"
  labels:
    {{- include ".helm.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-10"
