apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ include ".helm.fullname" . }}-ory-hydra-route"
  namespace: {{ .Values.namespace }}
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: (PathPrefix("/ory"))
      services:
        - name: "{{ .Release.Name }}-hydra-public"
          kind: Service
          port: 80
      middlewares:
      - name: "{{ include ".helm.fullname" . }}-ory-hydra-strip"