apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: "{{ include ".helm.fullname" . }}-ory-hydra-strip"
  namespace: {{ .Values.namespace }}
spec:
  stripPrefixRegex:
    regex:
      - "/ory"