apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ include ".helm.fullname" . }}-ory-keto-route"
  namespace: {{ .Values.namespace }}
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: (PathPrefix("/ory"))
      services:
        - name: "baseline-keto-read"
          kind: Service
          port: 80
      middlewares:
      - name: "{{ include ".helm.fullname" . }}-headers"
      - name: "{{ include ".helm.fullname" . }}-ory-keto-strip"