{{ if and (.Values.testStack.enabled) (.Values.testStack.serviceAccount.create) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include ".helm.testStackServiceAccountName" . }}
  namespace:
    "{{ .Values.namespace }}"
  labels:
    {{- include ".helm.labels" . | nindent 4 }}
  {{- with .Values.testStack.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{ end }}
