apiVersion: v1
kind: Service
metadata:
  name: {{ include ".helm.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include ".helm.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - name: discoveryrecvport
      protocol: UDP 
      port: {{ .Values.scs.containerPortRec }}
      targetPort: {{ .Values.scs.containerPortRec }}
    - name: discoverysendport
      protocol: UDP
      port: {{ .Values.scs.containerPortSend }}
      targetPort: {{ .Values.scs.containerPortSend }}
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
  {{- if .Values.scs.imagePullSecrets }}  
  externalIPs:
    - {{ .Values.scs.externalIps }}
   {{- end }}