scs:
  replicaCount: 1
  repository: ghcr.io/htaic/scsrun
  tag: latest
  pullPolicy: Always
  containerPortRec: 7711
  containerPortSend: 7701
  # externalIps: 123.123.123.123 # sets external IP for service

imagePullSecrets:
  - name: dockerconfigjson-github-com
  
resources:
  requests:
    cpu: 100m
    memory: 250Mi

serviceAccount:
  create: false
  annotations: {}
  name: ""
