fullnameOverride: "baseline"
enableTraefikDashboard: true

#TODO: edge environments should not need this
AWS:
  region: YOUR_AWS_REGION
  accountId: "YOUR_AWS_ACCOUNT_ID"

# https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
traefik:
  image:
    pullPolicy: Always
  service:
    type: LoadBalancer
  providers:
    kubernetesCRD:
      allowCrossNamespace: true

redis:
  redis:
    password: YOUR_REDIS_PASSWORD

postgresql:
  service:
    type: ClusterIP
  resources:
    requests:
      cpu: 100m
      memory: 250Mi
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
  postgres:
    db: postgres
    user: postgres
    password: YOUR_POSTGRES_PASSWORD
    authdb: auth
    authuser: auth_service
    authpassword: YOUR_AUTH_DB_PASSWORD
    replicaCount: 1
    repository: postgres
    tag: 14
    pullPolicy: Always
    containerPort: 5432
    env:
      # https://hub.docker.com/_/postgres
      - name: PGDATA
        value: /var/lib/postgresql/data/postgres # # To enable EFS on the cluster, use the following values in the root helm chart
    startUp:
      scriptContent: |
        apt update && apt install -y postgresql-14-wal2json
        sed -i 's/#wal_level = replica/wal_level = logical/g' /var/lib/postgresql/data/postgres/postgresql.conf
  # If using RDS for postgres
  # RDS:
  #   host: "YOUR_RDS_HOST"