fullnameOverride: "baseline"
enableTraefikDashboard: true

# https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
traefik:
  image:
    pullPolicy: Always
  service:
    type: LoadBalancer

redis:
  redis:
    replicaCount: 1
    repository: redis
    password: YOUR_REDIS_PASSWORD
    tag: latest
    pullPolicy: Always
    containerPort: 6379
  service:
    type: ClusterIP
  resources:
    requests:
      cpu: 250m
      memory: 750Mi
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80

postgresql:
  service:
    type: ClusterIP
  resources:
    requests:
      cpu: 250m
      memory: 750Mi
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
  postgres:
    db: postgres
    user: postgres
    password: YOUR_POSTGRES_PASSWORD
    auth-db: auth
    auth-user: auth_service
    auth-password: YOUR_AUTH_DB_PASSWORD
    replicaCount: 1
    repository: postgres
    tag: 14
    pullPolicy: Always
    containerPort: 5432
    env:
      # https://hub.docker.com/_/postgres
      - name: PGDATA
        value: /var/lib/postgresql/data/postgres # # To enable EFS on the cluster, use the following values in the root helm chart
