namespace: "hanwha"
fullnameOverride: distributor-devicemanager

image:
  replicaCount: 1
  repository: ghcr.io/htaic/distributor-devicemanager
  pullPolicy: Always
  tag: "latest"
  hostname: distributor-devicemanager
  containerPort: 3303
  envFrom:
    secretRefs:
      - baseline-redis-secret

imagePullSecrets:
  - name: dockerconfigjson-github-com

service:
  type: ClusterIP

resources:
  requests:
    cpu: 150m
    memory: 150Mi

serviceAccount:
  create: true
  annotations: {}
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
