apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-certs"
data:
  device.crt: |-
{{ .Values.cert.devicecrt | indent 4 }}
  device.key: |-
{{ .Values.cert.devicekey | indent 4 }}
  secret.key: |-
{{ .Values.cert.secretkey | indent 4 }}
