image:
  replicaCount: 1
  repository: ghcr.io/htaic/portlet-site-manager
  pullPolicy: Always
  containerPort: 3007
  tag: "latest"
  hostname: sitesmanager
  domainPath: "sites"
sidecarimage:
  name: "logging-sidecar"
  repository: ghcr.io/htaic/platform-logging-service
  pullPolicy: Always
  tag: "latest"
imagePullSecrets:
  - name: dockerconfigjson-github-com
service:
  type: ClusterIP
resources:
  requests:
    cpu: 100m
    memory: 250Mi
serviceAccount:
  create: false
  annotations: {}
  name: ""
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
