{{ if and (ne .Values.image.domainPath "") (hasKey .Values.image "domainPath") }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ include ".helm.fullname" . }}-route"
  namespace: {{ .Values.namespace }}
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: (Path("/{{ .Values.image.domainPath }}/{path:(login||realms/detect||logout||api(-json)?)}"))
      services:
        - name: {{ include ".helm.fullname" . }}
          kind: Service
          port: {{ .Values.image.containerPort }}
      {{ if (not (hasKey .Values.image "noStripPath")) }}
      middlewares:
      - name: "{{ include ".helm.fullname" . }}-strip"
      {{ end }}
    - kind: Rule
      match: (PathPrefix("/{{ .Values.image.domainPath }}"))
      services:
        - name: {{ include ".helm.fullname" . }}
          kind: Service
          port: {{ .Values.image.containerPort }}
      middlewares:
      - name: "{{ include ".helm.fullname" . }}-forward-auth"
      {{ if (not (hasKey .Values.image "noStripPath")) }}
      - name: "{{ include ".helm.fullname" . }}-strip"
      {{ end }}
{{ end }}