namespace: "hanwha"
fullnameOverride: anaheim-job-scheduler
domainPath: "job-scheduler"
forwardAuthaddress: http://anaheim-graphql-service-anaheim-authentication-service:9876/api/v1/validate
authResponseHeadersRegex Regex: ^X-
trustForwardHeader: true
licenseAuthaddress: http://anaheim-licensing-adapter:3029/license/status-middleware
image:
  replicaCount: 1
  repository: ghcr.io/htaic/anaheim-job-scheduler
  pullPolicy: Always
  containerPort: 3041
  tag: "latest"
  livenessProbe: healthcheck
  readinessProbe: healthcheck
  hostname: anaheim-job-scheduler
  env:
    - name: ENVIRONMENT
      value: " "
    - name: NODE_ENV
      value: "production"
    - name: APIURLPROJECTS
      value: "http://anaheim-project-service:3014"
    - name: GRAPHQLURL
      value: "http://anaheim-graphql-service-hasura:8080/v1/graphql"

imagePullSecrets:
  - name: dockerconfigjson-github-com

service:
  type: ClusterIP

resources:
  requests:
    cpu: 100m
    memory: 150Mi

serviceAccount:
  create: true
  annotations: {}
  name: ""

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

environments:
  wprod:
    projectenv: wprod
  wqa:
    projectenv: wqa
  wrelqa:
    projectenv: wrelqa
  wdev:
    projectenv: wdev
  wci:
    projectenv: wci

global:
  environment: production
