# apiVersion: traefik.containo.us/v1alpha1
# kind: Middleware
# metadata:
#   name: "{{ include ".helm.fullname" . }}-auth"
#   namespace: {{ .Values.namespace }}
# spec:
#   forwardAuth:
#     address: {{ .Values.forwardAuthaddress }}
#     authResponseHeadersRegex: {{ .Values.authResponseHeadersRegex }}
#     trustForwardHeader: {{ .Values.trustForwardHeader }}