apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ include ".helm.fullname" . }}-route"
  namespace: {{ .Values.namespace }}
spec:
  entryPoints:
    - web
  routes:
    - match: (PathPrefix("/{{ .Values.domainPath }}"))
      kind: Rule
      services:
        - name: {{ include ".helm.fullname" . }}
          kind: Service
          port: {{ .Values.image.containerPort }}
      {{ if (not (hasKey .Values "noStripPath")) }}
      middlewares:
      - name: "{{ include ".helm.fullname" . }}-strip"
      {{ if (not (hasKey .Values "noStripPath")) }}
      - name: "{{ include ".helm.fullname" . }}-strip"
      {{ end }}
