image:
  replicaCount: 1
  repository: ghcr.io/htaic/anaheim-portal/anaheim-container
  pullPolicy: Always
  containerPort: 3000
  tag: "0.0.222-0"
  livenessProbe: livez
  readinessProbe: readyz
  hostname: anaheim-container
  envFrom:
    secretRefs:
      - hasura-secret
  env:
    - name: GRAPHQLURL
      value: "http://anaheim-graphql-service-hasura:8080/v1/graphql"
    - name: GRAPHQLWSURL
      value: "wss://anaheim-graphql-service-hasura:8080/v1/graphql"

imagePullSecrets:
  - name: dockerconfigjson-github-com

service:
  type: ClusterIP

resources:
  requests:
    cpu: 100m
    memory: 300Mi

serviceAccount:
  create: true
  annotations: {}
  name: ""

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
