dcs:
  replicaCount: 1
  repository: ghcr.io/htaic/edgedcsmanagerrun
  tag: latest
  pullPolicy: Always
  containerPort: 5555

imagePullSecrets:
  - name: dockerconfigjson-github-com

service:
  type: ClusterIP

resources:
  requests:
    cpu: 250m
    memory: 750Mi

serviceAccount:
  create: false
  annotations: {}
  name: ""
  
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80