dcs:
  repository: ghcr.io/htaic/edgedcsmanagerrun
  tag: latest
  pullPolicy: Always

imagePullSecrets:
  - name: dockerconfigjson-github-com

resources:
  requests:
    cpu: 250m
    memory: 350Mi

serviceAccount:
  create: false
  annotations: {}
  name: ""
