# https://github.com/htaic/helm-charts/charts/microfrontend/values.yaml.example
namespace: "hanwha"
fullnameOverride: authmanager
image:
  replicaCount: 1
  repository: ghcr.io/htaic/authmanager
  pullPolicy: Always
  containerPort: 3002
  tag: "latest"
  hostname: authmanager
  domainPath: "login"
sidecarimage:
  name: "logging-sidecar"
  repository: ghcr.io/htaic/platform-logging-service
  pullPolicy: Always
  tag: "latest"
imagePullSecrets:
  - name: dockerconfigjson-github-com
service:
  type: ClusterIP
resources:
  requests:
    cpu: 150m
    memory: 350Mi
serviceAccount:
  create: false
  annotations: {}
  name: ""
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80