apiVersion: v1
kind: Secret
metadata:
  name: "{{ include ".helm.fullname" . }}-secret"
data:
  REDIS_PASSWORD: {{ .Values.redis.password | b64enc }}
stringData:
  REDIS_HOST: {{ .Values.redis.hostname }}
  REDIS_PORT: "{{ .Values.redis.containerPort }}"