apiVersion: v1
kind: Secret
metadata:
  name: "{{ include ".helm.fullname" . }}-secret"
data:
  REDIS_PASSWORD: {{ .Values.redis.password | b64enc }}
stringData:
  REDIS_PORT: "{{ .Values.redis.containerPort }}"
  {{- if (hasKey .Values.redis "hostname") }}
  REDIS_HOST: {{ .Values.redis.hostname }}
  {{- else }}
  REDIS_HOST: {{ include ".helm.fullname" . }}
  {{- end }}