apiVersion: v1
kind: Secret
metadata:
  name: "{{ include ".helm.fullname" . }}-secret"
data:
  REDISHOST: {{ .Values.redis.hostname }}
  REDISPORT: {{ .Values.redis.containerPort }}
  REDIS_PASSWORD: {{ .Values.redis.password | b64enc }}