image:
  replicaCount: 1
  repository: ghcr.io/htaic/portlet-roleservice
  pullPolicy: Always
  containerPort: 9877
  tag: "latest"
  domainPath: "roleservice"
  hostname: portlet-roleservice
    
imagePullSecrets:
  - name: dockerconfigjson-github-com
service:
  type: ClusterIP
resources:
  requests:
    cpu: 150m
    memory: 350Mi
serviceAccount:
  create: false
  annotations: {}
  name: ""
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
