{{ if and (ne .Values.edgeauth.domainPath "") (not (hasKey .Values.edgeauth "noStripPath")) }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: "{{ include ".helm.fullname" . }}-strip"
  namespace: {{ .Values.namespace }}
spec:
  stripPrefix:
    prefixes:
      - "/{{ .Values.edgeauth.domainPath }}"
{{ end }}