apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: redis
  repository: https://htaic.github.io/helm-charts
  version: ^0
- name: postgresql
  repository: https://htaic.github.io/helm-charts
  version: ^0
- name: dcs
  repository: file://./charts/dcs
  version: ^0
- name: edgeccs
  repository: file://./charts/edgeccs
  version: ^0
- name: scs
  repository: file://./charts/scs
  version: ^0
- name: keymanager
  repository: file://./charts/keymanager
  version: ^0
description: A dependent Helm chart for Kubernetes micro auth services
name: edge-services
type: application
version: 0.0.7
