edgeccs:
  repository: ghcr.io/htaic/edgeccs
  tag: latest
  pullPolicy: Always

imagePullSecrets:
  - name: dockerconfigjson-github-com

resources:
  requests:
    cpu: 100m
    memory: 250Mi

serviceAccount:
  create: false
  annotations: {}
  name: ""
