apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: redis
  repository: https://htaic.github.io/helm-charts
  version: ^0
- name: postgresql
  repository: https://htaic.github.io/helm-charts
  version: ^0
- name: edgeauth
  repository: file://./charts/edgeauth
  version: 0.0.1
- name: device-installer
  repository: file://./charts/device-installer
  version: 0.0.1
- name: graphql
  repository: file://./charts/graphql
  version: 0.0.1
description: A dependent Helm chart for Kubernetes micro auth services
name: edge-services-cloud
type: application
version: 0.0.4
