apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include ".helm.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include ".helm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.dcs.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include ".helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        date: "{{ now | unixEpoch }}"
        {{- include ".helm.selectorLabels" . | nindent 8 }}
    spec:
      hostname: {{ .Values.dcs.hostname }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include ".helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        {{- if .Values.sidecarimage }}
        - name: "{{ .Values.sidecardcs.name }}"
          image: "{{ .Values.sidecardcs.repository }}:{{ .Values.sidecardcs.tag }}"
          imagePullPolicy: {{ .Values.sidecardcs.pullPolicy }}
        {{- end }}      
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.dcs.repository }}:{{ .Values.dcs.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.dcs.pullPolicy }}
          {{- if .Values.dcs.env }}
          env: 
            {{- toYaml .Values.dcs.env | nindent 12 }}
          {{- end }}
          args: [ {{.Values.dcs.args}} ]
          ports:
            - name: http
              containerPort: {{ .Values.dcs.containerPort }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /{{ .Values.dcs.livenessProbe }}
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /{{ .Values.dcs.readinessProbe }}
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
