namespace: "hanwha"
fullnameOverride: anaheim-project-service
domainPath: "projects"
forwardAuthaddress: http://anaheim-graphql-service-anaheim-authentication-service:9876/api/v1/validate
authResponseHeadersRegex Regex: ^X-
trustForwardHeader: true
licenseAuthaddress: http://anaheim-licensing-adapter:3029/license/status-middleware
image:
  replicaCount: 1
  repository: ghcr.io/htaic/anaheim-project-service
  pullPolicy: Always
  containerPort: 3014
  tag: "latest"
  livenessProbe: healthcheck
  readinessProbe: healthcheck
  hostname: anaheim-project-service
  env:
    - name: ENVIRONMENT
      value: " "
    - name: GRAPHQLURL
      value: "http://anaheim-graphql-service-hasura:8080/v1/graphql"
    - name: API_ANNOTATION_SERVICE
      value: "http://anaheim-annotator-service:3012"
    - name: TRAINING_ASSETS_SERVICE_URL
      value: "http://anaheim-training-assets-service:3010"
    - name: CAN_RETRAIN_MINUTES
      value: "30"
    - name: IN_TRAINING_TO_ERROR_MINUTES
      value: "60"
      
imagePullSecrets:
  - name: dockerconfigjson-github-com

service:
  type: ClusterIP

resources:
  requests:
    cpu: 100m
    memory: 150Mi

serviceAccount:
  create: true
  annotations: {}
  name: ""

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
