namespace: "hanwha"
fullnameOverride: anaheim-project-service
domainPath: "projects"

image:
  replicaCount: 1
  repository: ghcr.io/htaic/anaheim-project-service
  pullPolicy: Always
  containerPort: 3014
  tag: "latest"
  livenessProbe: healthcheck
  readinessProbe: healthcheck
  hostname: anaheim-project-service
  envFrom:
    secretRefs:
      - hasura-secret
      - aws-eventbridge-secret
    configMapRefs:
      - aws-account-configmap
  env:
    - name: GRAPHQLURL
      value: "http://anaheim-graphql-service-hasura:8080/v1/graphql"
    - name: API_ANNOTATION_SERVICE
      value: "http://anaheim-annotator-service:3012"

imagePullSecrets:
  - name: dockerconfigjson-github-com

service:
  type: ClusterIP

resources:
  requests:
    cpu: 100m
    memory: 150Mi

serviceAccount:
  create: true
  annotations: {}
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
