namespace: "hanwha"
fullnameOverride: anaheim-project-service
domainPath: "projects"
forwardAuthaddress: http://anaheim-graphql-service-anaheim-authentication-service:9876/api/v1/validate
authResponseHeadersRegex Regex: ^X-
trustForwardHeader: true
image:
  replicaCount: 1
  repository: ghcr.io/htaic/anaheim-project-service
  pullPolicy: Always
  containerPort: 3014
  tag: "latest"
  livenessProbe: healthcheck
  readinessProbe: healthcheck
  hostname: anaheim-project-service
  env:
    - name: GRAPHQLURL
      value: "http://anaheim-graphql-service-hasura:8080/v1/graphql"
    - name: API_ANNOTATION_SERVICE
      value: "http://anaheim-annotator-service:3012"
    - name: TRAINING_ASSETS_SERVICE_URL
      value: "http://anaheim-training-assets-service:3010"
    - name: AWS_PROJECT_SQS_URL
      value: "https://sqs.${var.deploy_region}.amazonaws.com/${var.account_id}/pvt-sqs-wddl-${var.default_tags.Environment}-project-service-uw2-q"
    - name: AWS_PROJECT_SQS_NAME
      value: pvt-sqs-wddl-${var.default_tags.Environment}-project-service-uw2-q

imagePullSecrets:
  - name: dockerconfigjson-github-com

service:
  type: ClusterIP

resources:
  requests:
    cpu: 100m
    memory: 150Mi

serviceAccount:
  create: true
  annotations: {}
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
