image:
  replicaCount: 1
  repository: ghcr.io/htaic/portlet-group-manager
  pullPolicy: Always
  containerPort: 3006
  tag: "latest"
  hostname: groupsmanager
  domainPath: "groups"
sidecarimage:
  name: "logging-sidecar"
  repository: ghcr.io/htaic/platform-logging-service
  pullPolicy: Always
  tag: "latest"
imagePullSecrets:
  - name: dockerconfigjson-github-com
service:
  type: ClusterIP
resources:
  requests:
    cpu: 250m
    memory: 350Mi
serviceAccount:
  create: false
  annotations: {}
  name: ""
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
