apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include ".helm.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include ".helm.labels" . | nindent 4 }}
spec:
  {{- if not ((.Values.autoscaling).enabled) }}
  replicas: {{ ((.Values.image).replicaCount) }}
  {{- end }}
  selector:
    matchLabels:
      {{- include ".helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include ".helm.selectorLabels" . | nindent 8 }}
    spec:
      hostname: {{ .Values.image.hostname }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include ".helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.postgresUpdater }}
      initContainers:
        - name: {{ .Chart.Name }}-postgres-provisioner
          {{- if hasKey .Values.postgresUpdater "tag" }}
          image: {{ .Values.postgresUpdater.image }}:{{ .Values.postgresUpdater.tag }}
          {{ else }}
          image: {{ .Values.postgresUpdater.image }}:{{ .Values.image.tag }}
          {{ end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: APP_PASS
              value: {{ .Values.postgresUpdater.app_pass }}
          command: ['sh', '-c', '/home/developer/executecommands.sh']
          envFrom:
            - secretRef:
                name: "baseline-postgresql-secret"
            # TODO: Add cloud toggle for this    
            # - secretRef:
            #     name: "org-management-service-secret"
            - configMapRef:
                name: "baseline-configmap"
      {{- end }}
      containers:
        {{- if .Values.sidecarimage }}
        - name: "{{ .Values.sidecarimage.name }}"
          image: "{{ .Values.sidecarimage.repository }}:{{ .Values.sidecarimage.tag }}"
          imagePullPolicy: {{ .Values.sidecarimage.pullPolicy }}
        {{- end }}      
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.image.env }}
          env: 
            {{- toYaml .Values.image.env | nindent 12 }}
          {{- end }}
          args: [ {{.Values.image.args}} ]
          envFrom:
            - secretRef:
                name: "org-service-secret"
          ports:
            - name: http
              containerPort: {{ .Values.image.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /{{ .Values.image.livenessProbe }}
              port: http
          readinessProbe:
            httpGet:
              path: /{{ .Values.image.readinessProbe }}
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
