apiVersion: v1
kind: Secret
metadata:
  name: "auth-service-secret"
data:
  DATABASE_PASSWORD: "{{ .Values.postgresql.postgres.auth-password | b64enc }}"
stringData:
  DATABASE_NAME: {{ .Values.postgresql.postgres.auth-db }}
  DATABASE_USER: {{ .Values.postgresql.postgres.auth-user }}
  DATABASE_HOST: "{{ include ".helm.fullname" . }}-postgresql"