apiVersion: v1
kind: Secret
metadata:
  name: "iss-service-secret"
data:
  DATABASE_PASSWORD: {{ .Values.postgresql.postgres.isspassword | b64enc }}
stringData:
  DATABASE_NAME: {{ .Values.postgresql.postgres.issdb }}
  DATABASE_USER: {{ .Values.postgresql.postgres.issuser }}
