apiVersion: v1
kind: Secret
metadata:
  name: "org-service-secret"
data:
  DATABASE_PASSWORD: {{ .Values.postgresql.postgres.orgpassword | b64enc }}
stringData:
  DATABASE_NAME: {{ .Values.postgresql.postgres.orgdb }}
  DATABASE_USER: {{ .Values.postgresql.postgres.orguser }}
  DATABASE_HOST: "{{ include ".helm.fullname" . }}-postgresql"