apiVersion: v1
kind: Secret
metadata:
  name: "org-service-secret"
data:
  DATABASE_PASSWORD: {{ .Values.postgresql.postgres.password | b64enc }}
stringData:
  DATABASE_NAME: {{ .Values.postgresql.postgres.org-db }}
  DATABASE_USER: {{ .Values.postgresql.postgres.org-user }}
  DATABASE_HOST: "{{ include ".helm.fullname" . }}-postgresql"