namespace: "hanwha"
fullnameOverride: anaheim-annotator-service

image:
  replicaCount: 1
  repository: ghcr.io/htaic/anaheim-annotator-service
  pullPolicy: Always
  containerPort: 3012
  tag: "latest"
  hostname: anaheim-annotator-service
  domainPath: annotations
  envFrom:
    secretRefs:
      - hasura-secret
  env:
    - name: GRAPHQLURL
      value: "http://anaheim-graphql-service-hasura:8080/v1/graphql"

imagePullSecrets:
  - name: dockerconfigjson-github-com

service:
  type: ClusterIP

resources:
  requests:
    cpu: 100m
    memory: 150Mi

serviceAccount:
  create: true
  annotations: {}
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
