namespace: "hanwha"
fullnameOverride: anaheim-annotator-service
forwardAuthaddress: http://anaheim-graphql-service-anaheim-authentication-service:9876/api/v1/validate
authResponseHeadersRegex Regex: ^X-
trustForwardHeader: true
licenseAuthaddress: http://anaheim-licensing-adapter:3029/license/status-middleware

image:
  replicaCount: 1
  repository: ghcr.io/htaic/anaheim-annotator-service
  pullPolicy: Always
  containerPort: 3012
  tag: "latest"
  livenessProbe: livez
  readinessProbe: readyz
  hostname: anaheim-annotator-service
  domainPath: annotations
  envFrom:
    secretRefs:
      - hasura-secret
  env:
    - name: GRAPHQLURL
      value: "http://anaheim-graphql-service-hasura:8080/v1/graphql"
    - name: APIURLASSETS
      value: "http://anaheim-training-assets-service:3010"
    - name: APIURLPROJECTS
      value: "http://anaheim-project-service:3014"
    - name: SERVICE_ENV
      value: "non-local"

imagePullSecrets:
  - name: dockerconfigjson-github-com

service:
  type: ClusterIP

resources:
  requests:
    cpu: 100m
    memory: 150Mi

serviceAccount:
  create: true
  annotations: {}
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
