namespace: "hanwha"
fullnameOverride: foundationweb

image:
  replicaCount: 1
  repository: ghcr.io/htaic/foundationweb
  pullPolicy: Always
  containerPort: 3000
  tag: "latest"
  hostname: masterportal
sidecarimage:
  name: "logging-sidecar"
  repository: ghcr.io/htaic/platform-logging-service
  pullPolicy: Always
  tag: "latest"
imagePullSecrets:
  - name: dockerconfigjson-github-com
service:
  type: ClusterIP
resources:
  requests:
    cpu: 250m
    memory: 350Mi
serviceAccount:
  create: true
  annotations: {}
  name: ""
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80