apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  annotations:
    meta.helm.sh/release-name: {{ include ".helm.fullname" . }}-auth-manager
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  name: {{ include ".helm.fullname" . }}-auth-manager-traefik-middleware
  namespace: {{ .Values.namespace }}
spec:
  forwardAuth:
    address: /login
    authRequestHeaders:
    - accept
    - accept-encoding
    - cookie
    - x-session-token
    authResponseHeaders:
    - x-identity