apiVersion: v1
kind: Secret
metadata:
  name: "aws-sqs-secret"
data:
  AWS_SQS_NAME: {{ .Values.AWS.sqs_name | b64enc }}
  AWS_SQS_URL: {{ .Values.AWS.sqs_url | b64enc }}
  AWS_PROJECT_SQS_URL: {{ .Values.AWS.aws_project_sqs_name | b64enc }}
  AWS_PROJECT_SQS_NAME: {{ .Values.AWS.aws_project_sqs_name | b64enc }}
