apiVersion: v1
kind: ConfigMap
metadata:
  name: "aws-account-configmap"
data:
  AWS_REGION: {{ .Values.AWS.region }}
  AWS_ACCOUNT_ID: "{{ .Values.AWS.accountId }}"
  MODEL_S3_URI_PATH: {{ .Values.AWS.aws_model_s3_uri_path }}
