apiVersion: v1
kind: Secret
metadata:
  name: "aws-eventbridge-secret"
data:
  AWS_ACCESS_KEY: {{ .Values.AWS.event_bridge_key_id | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.AWS.event_bridge_key_secret | b64enc }}
  AWS_EVENT_BUS_ARN: {{ .Values.AWS.event_bus_arn | b64enc }}
  AWS_SQS_URL: {{ .Values.AWS.sqs_url_arn | b64enc }}
  AWS_SQS_NAME: {{ .Values.AWS.sqs_name | b64enc }}
