apiVersion: v1
kind: Secret
metadata:
  name: "datadog-secret"
data:
  VITE_DATADOG_CLIENT_TOKEN: {{ .Values.AWS.vite_datadog_client_token | b64enc }}
  VITE_DATADOG_URL: {{ .Values.AWS.vite_datadog_ur | b64enc }}
