apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson-github-com
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"ghcr.io\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.dockerCredentials.username .Values.dockerCredentials.token (printf "%s:%s" .Values.dockerCredentials.username .Values.dockerCredentials.token | b64enc) | b64enc | quote }}
