apiVersion: v1
kind: Secret
metadata:
  name: "hasura-secret"
data:
  hasuraToken: {{ .Values.graphql.hasuraToken | b64enc }}
  HASURA_GRAPHQL_ADMIN_SECRET: {{ .Values.graphql.hasuraToken | b64enc }}
