apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secrets"
data:
  DATABASE_PASSWORD: {{ .Values.postgresql.postgres.password | b64enc }}
stringData:
  DATABASE_USER: {{ .Values.postgresql.postgres.user }}


    
  