
imagePullSecrets: dockerconfigjson-github-com
namespace: hanwha

service:
  type: ClusterIP

scs:
  replicaCount: 1
  tag: latest
  image:
    repository: ghcr.io/htaic/scsrun
  resources:
    requests:
      cpu: 150m
      memory: 250Mi

keymanager:
  replicaCount: 1
  tag: latest
  image:
    repository: ghcr.io/htaic/edgekeymanagerrun
    env:
      - name: edgeId
        value: YOUR_EDGE_ID
  resources:
    requests:
      cpu: 150m
      memory: 450Mi

edgeccs:
  replicaCount: 1
  tag: latest
  image:
    repository: ghcr.io/htaic/edgeccs
    env:
      - name: edgeId
        value: YOUR_EDGE_ID
      - name: awsIotDataEndpoint
        value: YOUR_AWS_IOT_DATA_ENDPOINT
  resources:
    requests:
      cpu: 150m
      memory: 450Mi

dcs:
  replicaCount: 1
  tag: latest
  image:
    repository: ghcr.io/htaic/edgedcsmanagerrun
  resources:
    requests:
      cpu: 150m
      memory: 250Mi
