apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include ".helm.fullname" . }}-certs"
data:
{{ (.Files.Glob "certs/*").AsConfig | indent 2 }}
#   edge-awsRootCA1.pem.key: |
# {{ .Values.certs.awsRootCA1 | indent 4 }}
#   edge-awsRootCA3.pem.key: |
# {{ .Values.certs.awsRootCA3 | indent 4 }}
#   edge-certificate.pem.crt: |
# {{ .Values.certs.edgecertificate | indent 4 }}
#   edge-private.pem.key: |
# {{ .Values.certs.edgeprivate | indent 4 }}
#   edge-public.pem.key: |
# {{ .Values.certs.edgepublic | indent 4 }}
#   device_cert.zip: |
# {{ .Values.certs.awsRootCA1 | indent 4 }}
