{{- if .Values.dcs }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dcs
spec:
  replicas: {{ .Values.dcs.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include ".helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include ".helm.selectorLabels" . | nindent 8 }}
        app: dcs
    spec:
      containers:
        - name: dcs
          {{- if .Values.dcs.image.digest }}
          image: {{ .Values.dcs.image.repository }}@{{ .Values.dcs.image.digest }}
          {{- else }}
          image: {{ .Values.dcs.image.repository }}:latest
          {{- end }}
          imagePullPolicy: Always
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end }}
{{- end }}
