{{- if .Values.edgeccs }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edgeccs
spec:
  selector:
    matchLabels:
      app: edgeccs
  replicas: {{ .Values.edgeccs.replicaCount | default 1 }}
  template:
    metadata:
      labels:
        app: edgeccs
    spec:
      {{- if .Values.edgeccs.volume }}
      volumes:
        - name: {{ .Values.edgeccs.volume.pvcName }}
          persistentVolumeClaim:
            claimName: {{ .Values.edgeccs.volume.pvcName }}
      {{- end }}
      containers:
        - name: edgeccs
          {{- if .Values.edgeccs.image.digest }}
          image: {{ .Values.edgeccs.image.repository }}@{{ .Values.edgeccs.image.digest }}
          {{- else }}
          image: {{ .Values.edgeccs.image.repository }}:latest
          {{- end }}
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: "baseline-redis-secret"
          volumeMounts:
          - name: cert
            mountPath: /cert
      volumes:
        - name: cert
          configMap:
            name: "{{ include ".helm.fullname" . }}-certs"
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end }}
{{- end }}
