{{- if .Values.edgeccs }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edgeccs
spec:
  replicas: {{ .Values.edgeccs.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include ".helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include ".helm.selectorLabels" . | nindent 8 }}
        app: edgeccs
    spec:
      initContainers:
        - name: keymanager
          {{- if .Values.keymanager.image.tag }}
          image: {{ .Values.keymanager.image.repository }}@{{ .Values.keymanager.image.tag }}
          {{- else }}
          image: {{ .Values.keymanager.image.repository }}:latest
          {{- end }}
          imagePullPolicy: Always
          {{- if .Values.edgeccs.image.env }}
          env: 
            {{- toYaml .Values.edgeccs.image.env | nindent 12 }}
          {{- end }}          
          command: ['sh', '-c', 'cp -rH /cert/* /certLoader && ls -laR /certLoader']
          volumeMounts:
            - name: workdir
              mountPath: /certLoader
            - name: cert
              mountPath: /cert/device_cert
      containers:
        - name: edgeccs
          {{- if .Values.edgeccs.image.tag }}
          image: {{ .Values.edgeccs.image.repository }}@{{ .Values.edgeccs.image.tag }}
          {{- else }}
          image: {{ .Values.edgeccs.image.repository }}:latest
          {{- end }}
          imagePullPolicy: Always
          {{- if .Values.edgeccs.image.env }}
          env: 
            {{- toYaml .Values.edgeccs.image.env | nindent 12 }}
          {{- end }}
          envFrom:
            - secretRef:
                name: "baseline-redis-secret"
          volumeMounts:
          - name: workdir
            mountPath: /cert
      volumes:
        - name: workdir
          emptyDir: {}
        - name: cert
          configMap:
            name: "{{ include ".helm.fullname" . }}-certs"
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end }}
{{- end }}
