apiVersion: v1
kind: Service
metadata:
  name: edge-redis
  namespace: {{ .Values.namespace }}
  labels:
    {{- include ".helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: baseline
    app.kubernetes.io/name: redis
