{{ if .Values.storage }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: ubuntu:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - apt update && apt upgrade && apt install -y curl postgresql-client && curl {{ .Values.storage.scriptPath }} > {{ .Values.storage.volumeMountPath }}/dumpdb.sh && chmod +x {{ .Values.storage.volumeMountPath }}/dumpdb.sh && {{ .Values.storage.volumeMountPath }}/dumpdb.sh
            envFrom:
            - secretRef:
                name: "{{ include ".helm.fullname" . }}-secret"
            - configMapRef:
                name: "{{ .Chart.Name }}-configmap"
            volumeMounts:
            - name: postgres-vol
              mountPath: {{ .Values.storage.volumeMountPath }}
          restartPolicy: OnFailure
          volumes:
            - name: postgres-vol
              persistentVolumeClaim:
                claimName: "{{ include ".helm.fullname" . }}-claim"
{{ end }}