{{- if .Values.storage -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include ".helm.fullname" . }}-claim"
  namespace: {{ .Values.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storage.className }}
  resources:
    requests:
      storage: {{ .Values.storage.capacity }}
{{- end }}