apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-configmap"
data:
  POSTGRES_DB: {{ .Values.postgres.db }}
  POSTGRES_PORT: {{ .Values.postgres.containerPort }}
  {{- if (((.Values).RDS).host) }}
  POSTGRES_HOSTNAME: {{ .Values.RDS.host }}
  {{- else }}
  POSTGRES_HOSTNAME: {{ include ".helm.fullname" . }}
  {{- end }}