apiVersion: v1
kind: Secret
metadata:
  name: "{{ include ".helm.fullname" . }}-secret"
data:
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc }}
stringData:
  POSTGRES_USER: {{ .Values.postgres.user }}