graphql:
  replicaCount: 1
  repository: ghcr.io/htaic/gql-service
  tag: latest
  pullPolicy: Always
  containerPort: 3003
  domainPath: "graphql"
  env:
    - name: REDIS_HOST
      value: communication-service-redis
    - name: REDIS_PORT
      value: "6379"
      
imagePullSecrets:
  - name: dockerconfigjson-github-com

service:
  type: ClusterIP

resources:
  requests:
    cpu: 250m
    memory: 750Mi

serviceAccount:
  create: false
  annotations: {}
  name: ""
  
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80