apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  annotations:
    meta.helm.sh/release-name: baseline-oathkeeper
    meta.helm.sh/release-namespace: hanwha
  labels:
    app.kubernetes.io/managed-by: Helm
  name: baseline-oathkeeper-traefik-middleware
  namespace: hanwha
spec:
  forwardAuth:
    address: http://baseline-oathkeeper-api:4456/decisions
    authRequestHeaders:
    - accept
    - accept-encoding
    - cookie
    - x-session-token
    authResponseHeaders:
    - x-identity