apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  annotations:
    meta.helm.sh/release-name: baseline-auth-manager
    meta.helm.sh/release-namespace: hanwha
  labels:
    app.kubernetes.io/managed-by: Helm
  name: baseline-auth-manager-traefik-middleware
  namespace: hanwha
spec:
  forwardAuth:
    address: /login
    authRequestHeaders:
    - accept
    - accept-encoding
    - cookie
    - x-session-token
    authResponseHeaders:
    - x-identity