namespace: "hanwha"

postgres:
  user: postgres
  password: postgrespassword
  replicaCount: 1
  repository: postgres
  tag: 14
  pullPolicy: Always
  containerPort: 5432
  env:
    # https://hub.docker.com/_/postgres
    - name: PGDATA
      value: /var/lib/postgresql/data/pgdata

# Optional (should be passed in from parent chart)
storage:
  className: efs-storageclass
  provisioner: efs.csi.aws.com
  capacity: 20Gi
  volumeMode: Filesystem
  csi:
    volumeHandle: fs-055da45298ddc178f
    volumeAttributes:
      encryptInTransit: "true"
  # if you want to persist data without using backups use the PGDATA path from the postgres node
  volumeMountPath: /data

# Optional (should be passed in from parent chart... if you want to run a startup script, enter it here)
startUp:
  fileContent: |
      SELECT 'CREATE DATABASE ory '
      'WITH '
      'ENCODING = ''UTF8'' '
      'CONNECTION LIMIT = -1 '
      'IS_TEMPLATE = False'

service:
  type: ClusterIP

resources:
  requests:
    cpu: 250m
    memory: 750Mi

serviceAccount:
  create: false
  annotations: {}
  name: ""
  
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80