namespace: "hanwha"
fullnameOverride: gql-devicemanager

image:
  replicaCount: 1
  repository: ghcr.io/htaic/gql-devicemanager
  pullPolicy: Always
  containerPort: 3003
  tag: "latest"
  hostname: gql-devicemanager
  domainPath: "graphql"
  noStripPath: true
  env:
    - name: DATABASE_HOST
      value: "baseline-postgresql"
    - name: DATABASE_TYPE
      value: "postgres"
    - name: DATABASE_PORT
      value: "5432"
    - name: OPERATION_ENV
      value: "EDGE"
  envFrom:
    secretRefs:
      - baseline-redis-secret
      - graphql-postgresql-secret
    configMapRefs:
      - baseline-configmap

imagePullSecrets:
  - name: dockerconfigjson-github-com

service:
  type: ClusterIP

resources:
  requests:
    cpu: 100m
    memory: 150Mi

serviceAccount:
  create: true
  annotations: {}
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
