apiVersion: v2
name: baseline
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.8

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.0.1"

# kubeVersion: ">=1.17.0-0"

# This is where the helm chart will automatically pull content from a remote helm chart. Overrides
# can also be done for this so ensure naming overlap doesn't conflict or break your local or the remote
# helm chart dependency.
# https://helm.sh/docs/helm/helm_dependency/
# https://github.com/traefik/traefik-helm-chart
dependencies:
- name: traefik
  version: "10.24.2"
  repository: https://helm.traefik.io/traefik
- name: aws-efs-csi-driver
  version: "2.2.8"
  repository: https://kubernetes-sigs.github.io/aws-efs-csi-driver/
# the login page front end
- name: microfrontend
  version: "0.0.5"
  repository: "https://htaic.github.io/helm-charts"
# the auth service back end
- name: faux-auth-service
  version: "0.0.10"
  repository: "https://htaic.github.io/helm-charts"
  # repository: "file://../faux-auth-service"
# send logs out to open search
- name: filebeat
  version: "7.12.1"
  repository: https://helm.elastic.co
