apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: traefik
  repository: https://helm.traefik.io/traefik
  version: 10.24.2
- name: aws-efs-csi-driver
  repository: https://kubernetes-sigs.github.io/aws-efs-csi-driver/
  version: 2.2.8
- name: microfrontend
  repository: https://htaic.github.io/helm-charts
  version: 0.0.5
- name: faux-auth-service
  repository: https://htaic.github.io/helm-charts
  version: 0.0.10
- name: filebeat
  repository: https://helm.elastic.co
  version: 7.12.1
description: A Helm chart for Kubernetes
name: baseline
type: application
version: 0.0.9
