{{ if and (ne .Values.domainPath "") (hasKey .Values "domainPath") }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: "{{ include ".helm.fullname" . }}-validate"
  namespace: {{ .Values.namespace }}
spec:
  stripPrefixRegex:
    regex:
      - "/{{ .Values.domainPath }}/licensing-adapter/license/status-middleware"
{{ end }}