{{ if and (ne .Values.domainPath "") (hasKey .Values "domainPath") }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: "{{ include ".helm.fullname" . }}-validate"
  namespace: {{ .Values.namespace }}
spec:
  forwardAuth:
    address: {{ .Values.forwardAuthaddress }}
    authResponseHeadersRegex: {{ .Values.authResponseHeadersRegex }}
    trustForwardHeader: {{ .Values.trustForwardHeader }}
  # forwardAuth:
  #   address: /{{ .Values.domainPath }}/license/status-middleware"
  #   authResponseHeadersRegex: {{ .Values.authResponseHeadersRegex }}
  #   trustForwardHeader: {{ .Values.trustForwardHeader }}
{{ end }}