namespace: "hanwha"
fullnameOverride: anaheim-wavesync-adapter-service
domainPath: "wavesync-adapter"

image:
  replicaCount: 1
  repository: ghcr.io/htaic/anaheim-wavesync-adapter-service
  pullPolicy: Always
  containerPort: 3018
  tag: "latest"
  livenessProbe: healthcheck
  readinessProbe: healthcheck
  hostname: anaheim-wavesync-adapter-service
  env:
    - name: GRAPHQLURL
      value: "http://anaheim-graphql-service-hasura:8080/v1/graphql"
    - name: WAVESYNC_BASE_URL
      value: "https://sync.wavevms.com"
    - name: WAVESYNC_API_URL
      value: "relay.vmsproxy.com"
    - name: NODE_ENV
      value: "production"
    - name: TRAINING_ASSETS_SERVICE_URL
      value: "http://anaheim-training-assets-service:3010"
    - name: TOKEN_SECRET_KEY
      value: "xj6R2EgpS43K++fVPFfq1g+U+pgpMQzLOxn0rky9SiARNoxudStwhujil639BQIn"

imagePullSecrets:
  - name: dockerconfigjson-github-com

service:
  type: ClusterIP

resources:
  requests:
    cpu: 100m
    memory: 150Mi

serviceAccount:
  create: true
  annotations: {}
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
