namespace: 'hanwha'
fullnameOverride: kafka-rest-consumer-service

image:
  replicaCount: 1
  repository: ghcr.io/htaic/kafka-rest-consumer-service
  pullPolicy: Always
  tag: 'sha-525f2ef'
  secretref: 'auth-service-secret' # this is the secret where the database information will be pulled from
  env:
    - name: APP_DATA_VERSION
      value: '12'
    - name: KAFKA_REST_URL
      value: KAFKA_REST_PROXY_URL # this value is different between cloud and edge (edge has to go throuh internet to reach Traefik. In cloud, requests are made to Traefik's internal endpoint)
    - name: GROUP_NAME
      value: A_CONSUMER_GROUP_NAME # this must be unique per deployment instance. For example, cloud instance has a different value than any edge location.
    - name: LOG_LEVEL
      value: DEBUG
    - name: LOG_SINK
      value: STDOUT
    - name: LOG_WEBSOCKET_HOST
      value: localhost
    - name: LOG_WEBSOCKET_PORT
      value: '6420'
    - name: MAX_CONSUMER_RESTART_ATTEMPTS
      value: '3'
    - name: OPERATION_ENV
      value: 'edge'

##########################
# Caution updating below #
##########################
sidecarimage:
  name: 'logging-sidecar'
  repository: ghcr.io/htaic/platform-logging-service
  pullPolicy: Always
  tag: 'latest'

imagePullSecrets:
  - name: dockerconfigjson-github-com

resources:
  requests:
    cpu: 150m
    memory: 350Mi
