# #https://github.com/htaic/helm-charts/blob/main/charts/kafka-rest/values-dev.yaml
cp-kafka-rest:
  image: "confluentinc/cp-kafka-rest"
  imageTag: 6.1.0
  cp-kafka:
    bootstrapServers: YOUR_BOOTSTRAP_SERVERS
    resthostname: YOUR_KAFKA_REST_HOST_NAME
  prometheus:
    jmx:
      enabled: false ##Disable JMX
