namespace: "hanwha"
fullnameOverride: anaheim-feature-flags-service
domainPath: "feature-flags-service"
forwardAuthaddress: http://anaheim-graphql-service-anaheim-authentication-service:9876/api/v1/validate
trustForwardHeader: true
authResponseHeadersRegex: ^X-
image:
  replicaCount: 1
  repository: ghcr.io/htaic/anaheim-feature-flags-service
  pullPolicy: Always
  containerPort: 3020
  tag: "latest"
  livenessProbe: healthcheck
  readinessProbe: healthcheck
  hostname: anaheim-feature-flags-service
  env:
    - name: GRAPHQLURL
      value: "http://anaheim-graphql-service-hasura:8080/v1/graphql"

imagePullSecrets:
  - name: dockerconfigjson-github-com

service:
  type: ClusterIP

resources:
  requests:
    cpu: 100m
    memory: 150Mi

serviceAccount:
  create: true
  annotations: {}
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
