namespace: "hanwha"
fullnameOverride: rtsp-service

image:
  replicaCount: 1
  repository: ghcr.io/htaic/edge-rtsp-service
  pullPolicy: Always
  containerPort: 5554
  tag: "latest"
  domainPath: "stream"

##########################
# Caution updating below #
##########################
sidecarimage:
  name: "logging-sidecar"
  repository: ghcr.io/htaic/platform-logging-service
  pullPolicy: Always
  tag: "latest"
  
imagePullSecrets:
  - name: dockerconfigjson-github-com
  
service:
  type: ClusterIP

resources:
  requests:
    cpu: 100m
    memory: 150Mi

serviceAccount:
  create: true
  annotations: {}
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
