image:
  replicaCount: 1
  repository: ghcr.io/htaic/anaheim-portal/anaheim-verification-portlet
  pullPolicy: Always
  containerPort: 3002
  tag: "latest"
  hostname: anaheim-verification-portlet
  domainPath: "verify"

imagePullSecrets:
  - name: dockerconfigjson-github-com

service:
  type: ClusterIP

resources:
  requests:
    cpu: 100m
    memory: 150Mi

serviceAccount:
  create: true
  annotations: {}
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
