image:
  replicaCount: 3
  repository: ghcr.io/htaic/anaheim-portal/anaheim-verification-portlet
  pullPolicy: Always
  containerPort: 3002
  tag: "latest"
  livenessProbe: livez
  livenessProbePeriodSeconds: 240
  readinessProbe: readyz
  readinessProbePeriodSeconds: 240
  hostname: anaheim-verification-portlet
  domainPath: "verify"
  envFrom:
    secretRefs:
      - hasura-secret
  env:
    - name: GRAPHQLURL
      value: "http://anaheim-graphql-service-hasura:8080/v1/graphql"
    - name: GRAPHQLWSURL
      value: "wss://anaheim-graphql-service-hasura:8080/v1/graphql"

imagePullSecrets:
  - name: dockerconfigjson-github-com

service:
  type: ClusterIP

resources:
  requests:
    cpu: 100m
    memory: 300Mi

serviceAccount:
  create: true
  annotations: {}
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
