image:
  replicaCount: 1
  repository: ghcr.io/htaic/portlet-groupservice
  pullPolicy: Always
  containerPort: 4003
  tag: "latest"
  domainPath: "groupservice"
  hostname: portlet-groupservice
  livenessProbe: "api/v1/livez"
  readinessProbe: "api/v1/readyz"
  env:
  - name: LOGSINK
    value: STDOUT
  - name: NODE_ENV
    value: "development"
    
imagePullSecrets:
  - name: dockerconfigjson-github-com
service:
  type: ClusterIP
resources:
  requests:
    cpu: 150m
    memory: 250Mi
serviceAccount:
  create: false
  annotations: {}
  name: ""
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
