scs:
  replicaCount: 1
  repository: ghcr.io/htaic/scsrun
  tag: latest
  pullPolicy: Always
  containerPort: 7711

imagePullSecrets:
  - name: dockerconfigjson-github-com
  
resources:
  requests:
    cpu: 250m
    memory: 750Mi

serviceAccount:
  create: false
  annotations: {}
  name: ""
  
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80