image:
  replicaCount: 1
  repository: ghcr.io/htaic/portlet-orgservice
  pullPolicy: Always
  containerPort: 9877
  tag: "latest"
  domainPath: "orgservice"
  hostname: portlet-orgservice
    
imagePullSecrets:
  - name: dockerconfigjson-github-com
service:
  type: ClusterIP
resources:
  requests:
    cpu: 175m
    memory: 250Mi
serviceAccount:
  create: false
  annotations: {}
  name: ""
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
