apiVersion: v1
kind: Secret
metadata:
  name: "auth-service-secret"
data:
  DATABASE_PASSWORD: {{ .Values.postgresql.postgres.authpassword | b64enc }}
stringData:
  DATABASE_NAME: {{ .Values.postgresql.postgres.authdb }}
  DATABASE_USER: {{ .Values.postgresql.postgres.authuser }}
  DATABASE_HOST: "{{ include ".helm.fullname" . }}-postgresql"