apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}-auth-manager
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  name: {{ .Release.Name }}-auth-manager-traefik-middleware
  namespace: {{ .Release.Namespace }}
spec:
  forwardAuth:
    address: /login
    authRequestHeaders:
    - accept
    - accept-encoding
    - cookie
    - x-session-token
    authResponseHeaders:
    - x-identity