apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ include ".helm.fullname" . }}-dump"
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: postgres-dump
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command: ["/bin/bash"]
            args: ["-c", "/scripts/dump-cron.sh"]
            volumeMounts:
            - name: config
              mountPath: /scripts
            {{- if .Values.storage }}
            - name: postgres-vol
              mountPath: /var/lib/postgresql/data
            {{- end }}  
          volumes:
          {{- if .Values.storage }}
          - name: postgres-vol
            persistentVolumeClaim:
              claimName: {{ .Values.storage.claimName }}
          {{- end }}
          - name: config
            configMap:
              name: {{ .Release.Name }}-postgres-dump-configmap
# https://www.craftypenguins.net/blog/how-to-trigger-a-kubernetes-cronjob-manually/