apiVersion: v1
kind: Service
metadata:
  name: {{ include ".helm.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include ".helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.postgres.containerPort }}
      targetPort: {{ .Values.postgres.containerPort }}
      protocol: TCP
      name: http
  selector:
    {{- include ".helm.selectorLabels" . | nindent 4 }}
