{{ if and (ne .Values.image.domainPath "") (not (hasKey .Values.image "noStripPath")) }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: "{{ include ".helm.fullname" . }}-strip"
  namespace: {{ .Values.namespace }}
spec:
  headers:
    customResponseHeaders:
      X-Robots-Tag: "noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex"
  stripPrefix:
    prefixes:
      - "/{{ .Values.image.domainPath }}"
{{ end }}
