
namespace: "hanwha"
fullnameOverride: devicemanager

image:
  replicaCount: 1
  repository: ghcr.io/htaic/devicemanager
  pullPolicy: Always
  containerPort: 3001
  tag: "latest"
  hostname: devicemanager
  domainPath: "devicemanager"

sidecarimage:
  name: "logging-sidecar"
  repository: ghcr.io/htaic/platform-logging-service
  pullPolicy: Always
  tag: "latest"

imagePullSecrets:
  - name: dockerconfigjson-github-com

service:
  type: ClusterIP

resources:
  requests:
    cpu: 100m
    memory: 250Mi

serviceAccount:
  create: true
  annotations: {}
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80