image:
  replicaCount: 1
  repository: ghcr.io/htaic/portlet-orgservice-orchestrator
  pullPolicy: Always
  containerPort: 9876
  tag: "latest"
  domainPath: "orgcreate"
  hostname: portlet-orgservice-orchestrator
    
imagePullSecrets:
  - name: dockerconfigjson-github-com
service:
  type: ClusterIP
resources:
  requests:
    cpu: 250m
    memory: 350Mi
serviceAccount:
  create: false
  annotations: {}
  name: ""
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
