apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-certs"
data:
  device.crt: |-
{{ .Files.Get (printf "cert/device.crt") | indent 4 }}
  device.key: |-
{{ .Files.Get (printf "cert/device.key") | indent 4 }}
  secret.key: |-
{{ .Files.Get (printf "cert/secret.key") | indent 4 }}
