apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: organization-creation
  repository: file://./charts/organization-creation
  version: ^0
- name: organization-backend
  repository: file://./charts/organization-backend
  version: ^0
description: Helm chart for Organization Management front end service
name: organization-stack
type: application
version: 0.0.7
