apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ include ".helm.fullname" . }}-route"
  namespace: {{ .Values.namespace }}
spec:
  entryPoints:
    - web
  routes:
    - match: (PathPrefix("/{{ .Values.image.domainPath }}/healthcheck"))
      priority: 65
      kind: Rule
      services:
        - name: {{ include ".helm.fullname" . }}
          kind: Service
          port: {{ .Values.image.containerPort }}  
      middlewares:
      {{ if (not (hasKey .Values "noStripPath")) }}
      - name: "{{ include ".helm.fullname" . }}-strip"
      {{ end }}  
    - match: (PathPrefix("/{{ .Values.image.domainPath }}/api"))
      priority: 60
      kind: Rule
      services:
        - name: {{ include ".helm.fullname" . }}
          kind: Service
          port: {{ .Values.image.containerPort }}  
      middlewares:
      {{ if (not (hasKey .Values "noStripPath")) }}
      - name: "{{ include ".helm.fullname" . }}-strip"
      {{ end }}   
    - match: (PathPrefix("/{{ .Values.image.domainPath }}"))
      kind: Rule
      services:
        - name: {{ include ".helm.fullname" . }}
          kind: Service
          port: {{ .Values.image.containerPort }}
      middlewares:
      - name: "{{ include ".helm.fullname" . }}-secured"