hasura:
  replicaCount: 1
  repository: hasura/graphql-engine
  tag: v2.12.0
  pullPolicy: Always
  containerPort: 8080
  hostname: hasura
  env:
    - name: HASURA_GRAPHQL_METADATA_DATABASE_URL
      value: postgres://postgres:postgrespassword@faux-auth-service-postgres:5432/postgres
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
    - name: PG_DATABASE_URL
      value: postgres://postgres:postgrespassword@faux-auth-service-postgres:5432/postgres
      ## enable the console served by server
    - name: HASURA_GRAPHQL_ENABLE_CONSOLE
      value: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
    - name: HASURA_GRAPHQL_DEV_MODE
      value: "true"
    - name: HASURA_GRAPHQL_ENABLED_LOG_TYPES
      value: startup, http-log, webhook-log, websocket-log, query-log
      # We have a readonly role for all users other than Hasura GraphQL admin
    - name: HASURA_GRAPHQL_UNAUTHORIZED_ROLE
      value: readonly
      ## uncomment next line to set an admin secret
    - name: HASURA_GRAPHQL_ADMIN_SECRET
      value: ABCDEFGHIJKLMNOP

service:
  type: ClusterIP

resources:
  requests:
    cpu: 250m
    memory: 750Mi

serviceAccount:
  create: true
  annotations: {}
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80