namespace: "hanwha"
fullnameOverride: poc-frontend

image:
  replicaCount: 1
  repository: ghcr.io/htaic/poc-frontend
  pullPolicy: Always
  containerPort: 80
  tag: "latest"
  hostname: poc-frontend
imagePullSecrets:
  - name: dockerconfigjson-github-com
service:
  type: ClusterIP
resources:
  requests:
    cpu: 250m
    memory: 250Mi
serviceAccount:
  create: true
  annotations: {}
  name: ""
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80