namespace: "hanwha"

postgres:
  replicaCount: 1
  repository: postgres
  tag: 14
  pullPolicy: Always
  containerPort: 5432
  env:
    - name: POSTGRES_PASSWORD
      value: postgrespassword
    # https://hub.docker.com/_/postgres
    - name: PGDATA
      value: /var/lib/postgresql/data/pgdata

service:
  type: ClusterIP

resources:
  requests:
    cpu: 250m
    memory: 750Mi

serviceAccount:
  create: false
  annotations: {}
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80