# {{- if and .Values.storage (not (hasKey .Values.storage "disableCreate")) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include ".helm.fullname" . }}-claim"
  namespace: {{ .Values.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: {{ .Values.storage.capacity }}
# {{- end }}