apiVersion: v2
appVersion: 0.0.2
dependencies:
- name: postgresql
  repository: https://htaic.github.io/helm-charts
  version: 0.1.7
description: Helm chart for Organization Management service
name: org-service
type: application
version: 0.1.3
