apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: postgresql
  repository: https://htaic.github.io/helm-charts
  version: 0.1.2
- name: hasura
  repository: file://./dependency_chart/hasura
  version: 0.0.6
description: A Helm chart for Kubernetes micro auth services
name: faux-auth-service
type: application
version: 0.0.11
