apiVersion: v1
kind: Service
metadata:
  name: {{ include ".helm.fullname" . }}-verify
  namespace: {{ .Values.namespace }}
  labels:
    {{- include ".helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
      name: http
  selector:
    {{- include ".helm.selectorLabels" . | nindent 4 }}
