forwardAuthaddress: http://anaheim-graphql-service-anaheim-authentication-service:9876/api/v1/validate
authResponseHeadersRegex Regex: ^X-
trustForwardHeader: true
licenseAuthaddress: http://anaheim-licensing-adapter:3029/license/status-middleware

image:
  replicaCount: 1
  repository: ghcr.io/htaic/anaheim-portal/anaheim-training-portlet
  pullPolicy: Always
  containerPort: 3001
  tag: "latest"
  livenessProbe: livez
  livenessProbePeriodSeconds: 240
  readinessProbe: readyz
  readinessProbePeriodSeconds: 240
  hostname: anaheim-training-portlet
  domainPath: "training-portlet"
  envFrom:
    secretRefs:
      - hasura-secret
  env:
    - name: GRAPHQLURL
      value: "http://anaheim-graphql-service-hasura:8080/v1/graphql"
    - name: GRAPHQLWSURL
      value: "wss://anaheim-graphql-service-hasura:8080/v1/graphql"

imagePullSecrets:
  - name: dockerconfigjson-github-com

service:
  type: ClusterIP

resources:
  requests:
    cpu: 100m
    memory: 300Mi

serviceAccount:
  create: true
  annotations: {}
  name: ""

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

affinity:
  #Preferred if nodes are less please use this block
  podAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
     - weight: 100
       podAffinityTerm:
         labelSelector:
           matchExpressions:
           - key: app.kubernetes.io/name
             operator: In
             values:
               - anaheim-training-portlet
         topologyKey: "topology.kubernetes.io/zone"
  # podAffinity:
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #     - labelSelector:
  #         matchExpressions:
  #         - key: app.kubernetes.io/name
  #           operator: In
  #           values:
  #           - anaheim-training-portlet
  #       topologyKey: "topology.kubernetes.io/zone"

topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: "topology.kubernetes.io/zone"
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: anaheim-training-portlet
