forwardAuthaddress: http://anaheim-graphql-service-anaheim-authentication-service:9876/api/v1/validate
Auth Response Headers Regex: ^X-
Trust Forward Header: true
image:
  replicaCount: 1
  repository: ghcr.io/htaic/anaheim-portal/anaheim-training-portlet
  pullPolicy: Always
  containerPort: 3001
  tag: "latest"
  hostname: anaheim-training-portlet
  domainPath: "training"
  envFrom:
    secretRefs:
      - hasura-secret
  env:
    - name: GRAPHQLURL
      value: "http://anaheim-graphql-service-hasura:8080/v1/graphql"
    - name: GRAPHQLWSURL
      value: "wss://anaheim-graphql-service-hasura:8080/v1/graphql"

imagePullSecrets:
  - name: dockerconfigjson-github-com

service:
  type: ClusterIP

resources:
  requests:
    cpu: 100m
    memory: 300Mi

serviceAccount:
  create: true
  annotations: {}
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
