image:
  replicaCount: 1
  repository: ghcr.io/htaic/anaheim-portal/anaheim-training-portlet
  pullPolicy: Always
  containerPort: 3001
  tag: "latest"
  hostname: anaheim-portal/anaheim-training-portlet
  domainPath: "/training"

imagePullSecrets:
  - name: dockerconfigjson-github-com

service:
  type: ClusterIP

resources:
  requests:
    cpu: 100m
    memory: 150Mi

serviceAccount:
  create: true
  annotations: {}
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
