namespace: "hanwha"
fullnameOverride: anaheim-training-assets-service
domainPath: "assets"


image:
  replicaCount: 1
  repository: ghcr.io/htaic/anaheim-training-assets-service
  pullPolicy: Always
  containerPort: 3010
  tag: "latest"
  hostname: anaheim-training-assets-service
  envFrom:
    secretRefs:
      - hasura-secret
  env:
    - name: GRAPHQLURL
      value: "http://hasura:8080/v1/graphql"
    - name: STORAGE_BASE_PATH
      value: "/assets"

imagePullSecrets:
  - name: dockerconfigjson-github-com

service:
  type: ClusterIP

resources:
  requests:
    cpu: 100m
    memory: 150Mi

serviceAccount:
  create: true
  annotations: {}
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

storage:
  className: efs-storageclass
  provisioner: efs.csi.aws.com
  capacity: 50Gi
  volumeMode: Filesystem
  csi:
    volumeHandle: YOUR_FILESYSTEM_ID
    volumeAttributes:
      encryptInTransit: "true"
  volumeMountPath: /assets
