namespace: "hanwha"
fullnameOverride: anaheim-training-assets-service
domainPath: "training-assets"
forwardAuthaddress: http://anaheim-graphql-service-anaheim-authentication-service:9876/api/v1/validate
trustForwardHeader: true
authResponseHeadersRegex: ^X-
image:
  replicaCount: 1
  repository: ghcr.io/htaic/anaheim-training-assets-service
  pullPolicy: Always
  containerPort: 3010
  tag: "latest"
  hostname: anaheim-training-assets-service

  env:
    - name: GRAPHQLURL
      value: "http://anaheim-graphql-service-hasura:8080/v1/graphql"
    - name: STORAGE_BASE_PATH
      value: "/assets"
    - name: FF_SHARE_ACROSS_VERSION
      value: "false"
    - name: FEATURE_FLAGS_API_URL
      value: "https://pvt-k8s-hv-wdev-wddl-uw2-1.wdev.hticdev.net/feature-flags-service"

imagePullSecrets:
  - name: dockerconfigjson-github-com

service:
  type: ClusterIP

resources:
  requests:
    cpu: 100m
    memory: 150Mi

serviceAccount:
  create: true
  annotations: {}
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

storage:
  className: efs-storageclass
  provisioner: efs.csi.aws.com
  capacity: 100Gi
  volumeMode: Filesystem
  csi:
    volumeHandle: fs-0ba685ad88487dfee
    volumeAttributes:
      encryptInTransit: "true"
  volumeMountPath: /assets
