namespace: "hanwha"
fullnameOverride: anaheim-training-assets-service
domainPath: "training-assets"
forwardAuthaddress: http://anaheim-graphql-service-anaheim-authentication-service:9876/api/v1/validate
authResponseHeadersRegex Regex: ^X-
trustForwardHeader: true
licenseAuthaddress: http://anaheim-licensing-adapter:3029/license/status-middleware

image:
  replicaCount: 1
  repository: ghcr.io/htaic/anaheim-training-assets-service
  pullPolicy: Always
  containerPort: 3010
  tag: latest
  livenessProbe: healthcheck
  readinessProbe: healthcheck
  hostname: anaheim-training-assets-service

  env:
    - name: PROJECTS_API_URL
      value: "http://anaheim-project-service:3014"
    - name: GRAPHQLURL
      value: "http://anaheim-graphql-service-hasura:8080/v1/graphql"
    - name: STORAGE_BASE_PATH
      value: "/assets"
    - name: FEATURE_FLAGS_API_URL
      value: "http://anaheim-feature-flags-service:3020"
    - name: PROJECTS_API_URL
      value: "http://anaheim-project-service:3014"

imagePullSecrets:
  - name: dockerconfigjson-github-com

service:
  type: ClusterIP

resources:
  requests:
    cpu: 100m
    memory: 150Mi

serviceAccount:
  create: true
  annotations: {}
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

storage:
  className: efs-storageclass
  provisioner: efs.csi.aws.com
  capacity: 100Gi
  volumeMode: Filesystem
  csi:
    volumeHandle: YOUR_FILESYSTEM_ID
    volumeAttributes:
      encryptInTransit: "true"
  volumeMountPath: /assets
